apiVersion: v1
kind: Template
metadata:
  annotations:
    description: Build Pipeline
    iconClass: icon-jboss
    tags: java,springboot,fis,eap,secret,build
  name: build-pipeline
objects:
 - apiVersion: v1
   kind: "BuildConfig"
   apiVersion: "v1"
   metadata:
     name: "${APP_NAME}-pipeline"
   spec:
     source:
       git:
         uri: "https://gogs-cicd-tools.cloud.sfb/banestes/default-pipelines"
       sourceSecret:
         name: "gogs-secret"
     strategy:
       jenkinsPipelineStrategy:
         jenkinsfilePath: ${JENKINS_FILE}
         env:
         - name: "NAMESPACE_DEV"
           value: ${NAMESPACE_BASE}-dev
         - name: "NAMESPACE_UAT"
           value: ${NAMESPACE_BASE}-uat
         - name: "NAMESPACE_PRD"
           value: ${NAMESPACE_BASE}
         - name: "APP_NAME"
           value: ${APP_NAME}
         - name: "APP_GIT_URL"
           value: ${APP_GIT_URL}
         - name: "BRANCH"
           value: ${BRANCH}
         - name: "VERSION"
           value: "${VERSION}"
         - name: "CONFIGMAP_URL"
           value: "${CONFIGMAP_URL}"
         - name: "SECRET_URL"
           value: ${SECRET_URL}
         - name: "VERSION"
           value: "${VERSION}"
         - name: "DEBUG_WORKFLOW"
           value: "${DEBUG_WORKFLOW}"
         - name: "INTROSCOPE_SERVER_NAME"
           value: "${INTROSCOPE_SERVER_NAME}"
         - name: "IMAGE_STREAM"
           value: "${IMAGE_STREAM}"
         - name: "TEMPLATE"
           value: "${TEMPLATE}"
         - name: "TOKEN"
           value: "${TOKEN}"
parameters:
- description: Application Name
  displayName: Application Name
  name: APP_NAME
- description: Namespace
  displayName: Namespace
  name: NAMESPACE_BASE
- description: Git URL
  displayName: Git URL
  name: APP_GIT_URL
- description: Jenkins Files
  displayName: Jenkins Files
  name: JENKINS_FILE
- description: Sufix
  displayName: Sufix
  name: SUFIX
  value: ''
- description: Branch
  displayName: Branch
  name: BRANCH
  value: 'develp'
- description: Version
  displayName: Version
  name: VERSION
  value: 'XX'
- description: ConfigMap URL
  displayName: ConfigMap URL
  name: CONFIGMAP_URL
  value: 'NONE'
- description: Secret URL
  displayName: Secret URL
  name: SECRET_URL
  value: 'NONE'
- description: Debug workflow (Y/N)
  displayName: Debug workflow
  name: DEBUG_WORKFLOW
  value: 'N'
- description: Introscope Server Name
  displayName: Introscope Server Name
  name: INTROSCOPE_SERVER_NAME
  value: 'demopolis.banestes.sfb'
- description: ImageStream with version
  displayName: ImageStream
  name: IMAGE_STREAM
  required: true
- description: Template
  displayName: Template
  name: TEMPLATE
  required: true
- desciption: Token de autorização
  displayName: Token de autorização
  name: TOKEN
  required: true
