apiVersion: v1
kind: Template
metadata:
  annotations:
    description: Build Pipeline
    iconClass: icon-jboss
    tags: java,springboot,fis,eap,secret,build
  name: build-pipeline
objects:
 - apiVersion: v1
   kind: "BuildConfig"
   apiVersion: "v1"
   metadata:
     name: "${APP_NAME}${SUFIX}"
   spec:
     source:
       git:
         uri: "http://gogs-banestes-cicd-tools.apps.rh-consulting-br.com/banestes/default-pipelines"
     strategy:
       jenkinsPipelineStrategy:
         jenkinsfilePath: ${JENKINS_FILE}
         env:
         - name: "NAMESPACE_DEV"
           value: ${NAMESPACE_BASE}-dev
         - name: "NAMESPACE_HML"
           value: ${NAMESPACE_BASE}-hml
         - name: "NAMESPACE_PRD"
           value: ${NAMESPACE_BASE}
         - name: "APP_NAME"
           value: ${APP_NAME}
         - name: "GIT_URL"
           value: ${GIT_URL}
     output:
       to:
         kind: "ImageStreamTag"
         name: "${APP_NAME}:latest"
parameters:
- description: Application Name
  displayName: Application Name
  name: APP_NAME
- description: Namespace
  displayName: Namespace
  name: NAMESPACE_BASE
- description: Git URL
  displayName: Git URL
  name: GIT_URL
- description: Jenkins Files
  displayName: Jenkins Files
  name: JENKINS_FILE
- description: Sufix
  displayName: Sufix
  name: SUFIX
  value: ''