apiVersion: v1
kind: Template
metadata:
    tags: instant-app,jenkins
  name: dev-hml-pipeline
objects:
 - apiVersion: v1
   kind: "BuildConfig"
   apiVersion: "v1"
   metadata:
     name: "dev-hml-pipeline"
   spec:
     source:
       git:
         uri: "http://gogs-banestes-cicd-tools.apps.rh-consulting-br.com/banestes/default-pipelines/pipelines"
     strategy:
       jenkinsPipelineStrategy:
         jenkinsfilePath: Jenkinsfile-Dev-Hml
         env:
         - name: "PROJECT_NAME"
           value: ${NAMESPACE}
         - name: "APP_NAME"
           value: ${APP_NAME}
     output:
       to:
         kind: "ImageStreamTag"
         name: "${APP_NAME}:latest"
parameters:
- description: Application Name
  displayName: Application Name
  name: APP_NAME
- description: Namespace
  displayName: Namespace
  name: NAMESPACE